# Generated by Django 6.1.1 on 2026-09-24 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 24, 14, 33, 38, 370005, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Inscripción'),
            preserve_default=False,
        ),
    ]
